name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them.'
inputs:
  caching: #NAME IS OF OUR CHOICE
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether cache was used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Caching dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4.0.1
      with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}  
    - name: install NodeJS
      uses: actions/setup-node@v4.0.2
      with:
         node-version: 18
    - name: install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash #shell needs to be provided while using run