name: custom composite actions
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4.1.1
        - name: Load & Cache Dependencies
          uses: ./.github/actions/cached-dependencies
          with:
            caching: 'false'
        - name: Lint Code
          run: npm run lint          

  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4.1.1
        - name: Load & Cache Dependencies
          uses: ./.github/actions/cached-dependencies
        - name: Run tests
          id: run-tests
          run: npm test          
        - name: Upload Test Report
          if: success() && steps.run-tests.outcome == 'successful'
          uses: actions/upload-artifact@v4.3.1
          with:
            name: test-report
            path: test.json    
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
        scripts-file: ${{ steps.publish.outputs.script-file }}
    steps:
        - name: checkout code
          uses: actions/checkout@v4.1.1
        - name: Caching dependencies
          uses: actions/cache@v4.0.1
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: install dependencies
          run: npm ci        
        - name: Build Project
          run: npm run build
        - name: publish JS filename
          id: publish
          run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'  
        - name: upload artifacts
          uses: actions/upload-artifact@v4.3.1
          with:
            name: dist-files-react
            path: dist
                # dist
                # package.json
                
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Deploy
          run: echo "Artifact Deployed"
  